name: seaside_blocs
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  bloc:
  firebase_abstraction:
    path: ../firebase_abstraction
  tuple:
  equatable:
  shared_preferences:

dev_dependencies:
  test: ">=1.3.0 <2.0.0"
  test_coverage: ^0.2.0
  mockito: ^4.0.0